# Generated by Django 5.2.4 on 2025-07-28 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book_Api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publish_data',
            new_name='publish_date',
        ),
    ]
