# Generated by Django 4.1.3 on 2025-07-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descriptipon', models.TextField(null=True)),
                ('imageUrl', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('isActive', models.BooleanField()),
                ('isUpdated', models.BooleanField()),
            ],
        ),
    ]
