# Generated by Django 4.1.3 on 2025-07-22 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='descriptipon',
            new_name='description',
        ),
    ]
