# Generated by Django 4.1.3 on 2025-07-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0008_alter_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
