# Generated by Django 4.1.3 on 2025-07-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0011_course_ishome_alter_course_isactive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
